service: awscovidbot2


provider:
  name: aws
  runtime: nodejs12.x


functions:
  awscovidbot2:
  
    handler: handler.covidbot
    
    events:

      - http:

          path: covidbot

          method: post

          cors: true